apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: phonebook
  labels:
    app: backend
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        env: test
    spec:
      containers:
      - name: backend
        image: localhost:80/be:v1.0.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-config
          mountPath: /app/config
      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
          - key: fronend-url
          - key: database-url
            path: .env
